### ISSUE TITLE
Support for API Gateway

### ISSUE THREAD

**Issue by shantanuo** [theserverlessway/awsinfo#104]
List of all API and their end-points with config details in tabular format will be very useful.

**Comment by flomotlik** [comment]
Hi, thanks for reporting. I'm currently super deep in a customer project and don't think I'll be able to get around to it soonish, but I added lot more documentation around the Scripts and Contributing, so maybe you're able to send a quick PR? https://github.com/theserverlessway/awsinfo/blob/master/CONTRIBUTING.md
