### ISSUE TITLE
Use environment bash instead of /bin/bash

### ISSUE THREAD

**Issue by kerma** [theserverlessway/awsinfo#94]
It may happen that a particular system has multiple bash versions installed (thanks, Apple). awsinfo should use the environment bash (`/usr/bin/env bash`), instead of `/bin/bash`.

https://github.com/theserverlessway/awsinfo/blob/7881691e46f05a2f5c09a85011ea965cca70207c/scripts/awsinfo.bash#L1

**Comment by flomotlik** [comment]
Yup that makes sense. Although I would highly recommend to use the Docker container as AWSInfo is pretty specific about the Bash version (and other tools, e.g. OSX date will be an issue for logs for example.)

**Comment by flomotlik** [comment]
Merged change now, thanks for the idea

**Comment by kerma** [comment]
Thanks 👍 

I was using it actually via docker until now. Moved to using the bash directly as the performance differs and I don't keep the docker daemon running constantly.

**Comment by flomotlik** [comment]
Let me know if there are any other issues with running it outside of Docker. Definitely want this to be solid without Docker as well (will try myself as well, lets see how it goes).
