### ISSUE TITLE
Support for CodePipeline

### ISSUE THREAD

**Issue by TLaue** [theserverlessway/awsinfo#99]
Support for CodePipeline service with following commands:
- get-pipeline
- get-pipeline-execution
- get-pipeline-state
- list-pipelines
- list-pipeline-executions

Thank you very much in advance.

**Comment by flomotlik** [comment]
Hi, thanks for reporting and sorry I didn't reply earlier. I'm currently super deep in a customer project and don't think I'll be able to get around to it soonish, but I added lot more documentation around the Scripts and Contributing, so maybe you're able to send a quick PR? https://github.com/theserverlessway/awsinfo/blob/master/CONTRIBUTING.md

**Comment by TLaue** [comment]
Hi, I will try to send a PR somewhen during the next weeks - depending on my spare time possibilitites.

**Comment by flomotlik** [comment]
Thanks! If any questions come up let me know

**Comment by flomotlik** [comment]
Support has been implemented.
